name: 'Deploy Dev Environment'

on:
  push:
    branches:
      - dev
    paths:
      - 'docs/**'
      - 'packages/**'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
        with:
          ref: dev  # 确保使用 dev 分支

      - name: 安装pnpm
        uses: pnpm/action-setup@v2

      - name: 安装根目录依赖
        run: pnpm install --no-frozen-lockfile

      - name: 安装文档依赖
        run: pnpm -C docs install --no-frozen-lockfile

      - name: 构建组件库（开发环境）
        run: pnpm run build

      - name: 构建文档
        run: pnpm run docs:build

      - name: 部署到开发环境
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: 'docs/docs-dist'
          clean: true  # 不清理，保留 master 分支的部署
