name: Release Package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/package.json'  # 如果是 monorepo，监听所有子包的 package.json

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，用于版本计算
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org/
          
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
          
      - name: 安装依赖(跳过锁文件检查)
        run: pnpm install --no-frozen-lockfile

      - name: 项目测试
        run: pnpm run test

      - name: 构建项目
        run: pnpm run build
        
      - name: 创建版本号
        run: npx changeset version --snapshot ${{ github.event.inputs.release-type }}
      
      - name: 登录到npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          
      - name: 发布到npm
        run: npx changeset publish --only ease-reactify
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}