name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4  # 必须有uses来获取代码

      - name: 安装依赖
        run: pnpm install  # 运行pnpm install来安装依赖

      - name: 项目测试
        run: pnpm run test  # 运行pnpm测试项目

      - name: 构建项目
        run: pnpm run docs:build  # 运行构建文档的命令

      - name: 部署GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # 使用GitHub Actions来部署到gh-pages
        with:
          branch: gh-pages  # 指定部署的分支
          folder: '/docs/dist'  # 指定构建后的文件夹路径
          clean: true  # 清理旧的部署文件