name: Deploy Docs

on:
  push:
    branches:
        - main

jobs:
  build-and-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: 读取仓库内容
     - uses: actions/checkout@v4

     - name: 安装依赖
     - run: pnpm install

     - name: 项目测试
     - run: pnpm run test

     - name: 构建项目
     - run: pnpm run docs:build

     - name: 部署GitHub Pages
     - uses: JamesIves/github-pages-deploy-action@v4
     - with:
        branch: gh-pages
        folder: '/docs/dist'